Repository abdelh17/Quolance, pull requests merged in 2024-12, with the labels that each got.

#175 README-Added teammate
  README.md
Labels: README

#166 [Frontend] #133: Work on UI to reject applicants
  quolance-ui/src/api/auth-api.ts
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/api/projects-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/CreateAdminForm.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectApplication.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/components/container.tsx
  quolance-ui/src/components/error-feedback.tsx
  quolance-ui/src/components/ui/RichTextDisplay.tsx
  quolance-ui/src/components/ui/RichTextEditor.tsx
  quolance-ui/src/components/ui/Tooltip.tsx
  quolance-ui/src/components/ui/ViewEditField.tsx
  quolance-ui/src/components/ui/button.tsx
  quolance-ui/src/components/ui/dropdown-menu.tsx
  quolance-ui/src/components/ui/form.tsx
  quolance-ui/src/components/ui/freelancers/BasicFreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/FreelancersFilterModal.tsx
  quolance-ui/src/components/ui/freelancers/freelancerCardStyles.css
  quolance-ui/src/components/ui/input.tsx
  quolance-ui/src/components/ui/label.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsContent.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/components/ui/projects/ProjectStatusBadge.tsx
  quolance-ui/src/components/ui/separator.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/models/applications/ApplicationResponse.ts
  quolance-ui/src/constants/types/project-types.ts
  quolance-ui/src/lib/utils.ts
  quolance-ui/src/public/images/freelancer_default_icon.png
  quolance-ui/src/util/CandidateSelectionUtils.tsx
  quolance-ui/src/util/utils.ts
Labels: candidate selection, frontend

#179 test: Integration tests for ClientController operations and CICD pipeline fix for #169
  .github/workflows/main.yml
  quolance-api/pom.xml
  quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/controllers/ClientControllerIT.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/controllers/FreelancerControllerIT.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/ProjectServiceTest.java
  quolance-api/src/test/resources/application-test.yml
Labels: testing

#183 test: Integration tests for FreelancerController operations for #169
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/EntityCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AbstractTestcontainers.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
Labels: backend, testing

#184 test: Integration tests for AdminController operations for #169
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/EntityCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
Labels: backend, testing

#186 test: Integration tests for AuthController operations for #169
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/AuthServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java
Labels: testing

#188 cicd: Added Sonar Cloud to the pipeline for code quality scans
  .github/workflows/main-branch-analysis.yml
  .github/workflows/main.yml
  quolance-api/pom.xml
  quolance-ui/sonar-project.properties
Labels: technology

#192 test: Integration tests for UserController operations for #169
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/CreateAdminRequestDto.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
Labels: backend, testing

#191 bugfix: Validate empty strings in project update
  README.md
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
Labels: bug, backend

#190 test: Added unit tests for Admin, Auth, Client and Freelancer Controllers
  quolance-api/src/test/java/com/quolance/quolance_api/unit/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/FreelancerControllerUnitTest.java
Labels: backend, testing

#194 Completed implementation of controllers unit tests #193
  quolance-api/src/test/java/com/quolance/quolance_api/unit/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/EnumControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/PendingControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/PublicControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/UsersControllerUnitTest.java
Labels: backend, testing

#199 Implemented unit tests for jobs
  quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendResetPasswordEmailUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendTempPasswordEmailUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendWelcomeEmailUnitTest.java
Labels: backend, testing

#196 Implemented unit tests for services
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/EnumControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PendingControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/UsersControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ApplicationProcessWorkflowUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ApplicationServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
Labels: backend, testing

#215 feat: Implement and Secure WebSocket STOMP Integration for #173
  infrastructure/Caddyfile
  quolance-api/pom.xml
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/WebSocketConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/WebSocketController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/ChatResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/GreetingResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/NotificationResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/MessageEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/MessageRepository.java
  quolance-api/src/main/resources/application.yml
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/websockettest/page.tsx
Labels: frontend, backend, Notifications

#205 feat: Rework frontend registration flow for #176
  quolance-ui/src/api/auth-api.ts
  quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/AuthHeader.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/RadioCardUser.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/shared/auth-components.tsx
  quolance-ui/src/components/ui/button.tsx
Labels: user authentication, frontend

#218 feat: Frontend make UI for freelancer to cancel application
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/ui/Modal.tsx
  quolance-ui/src/components/ui/button.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
Labels: proposal submission, frontend

#211 feat: Implemented backend blog functionalities for creating/retrieval of blogs for #125
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/BlogThreadViewController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogThreadViewRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogThreadViewResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/UpdateBlogThreadViewTitleDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/BlogPost.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/BlogThreadView.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/BlogPostRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/BlogThreadViewRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/BlogPostService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/BlogThreadViewService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogThreadViewServiceImpl.java
Labels: backend
