Repository abdelh17/Quolance, pull requests merged in 2024-11, with the labels that each got.

#71 (feat) #70: Added docker set-up scripts and updated readme
  README.md
  infrastructure/docker-compose.yaml
  quolance-api/src/main/resources/application.properties
  quolance-api/src/main/resources/application.yml
  scripts/quolance.sh
Labels: README, technology

#78 [#69] [FE] - Implemented Registration, Role-Based Access, and Profile Updates with Styling Fixes
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/freelancers/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-basic-details-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-password-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login-success/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
  quolance-ui/src/app/(without-main-layout)/sign-in/page.tsx
  quolance-ui/src/app/(without-main-layout)/sign-up/page.tsx
  quolance-ui/src/app/auth/register/components/register-form.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/app/profile/page.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/components/home/HeroSection.tsx
  quolance-ui/src/components/permission-guard.tsx
  quolance-ui/src/components/role-guard.tsx
  quolance-ui/src/components/success-feedback.tsx
  quolance-ui/src/components/ui/button.tsx
  quolance-ui/src/components/ui/dropdown-menu.tsx
  quolance-ui/src/components/ui/form.tsx
  quolance-ui/src/components/ui/input.tsx
  quolance-ui/src/models/user/UserResponse.ts
Labels: user authentication, frontend

#82 29 BE Admin can create admin
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/CreateAdminRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/SecurityUtil.java
Labels: backend

#84 33 Admin can approve/reject a pending project
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/RejectProjectRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProjectStatus.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/AdminService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/AdminServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java
Labels: backend

#83 [Frontend] #64: Connect UI to backend freelancer applying to project
  quolance-ui/src/api/auth-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/my-projects/ClientProjectsView.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/my-projects/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/freelancers/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-basic-details-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-password-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectApplication.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/post-project/page.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/error-feedback.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/components/permission-guard.tsx
  quolance-ui/src/components/postProjectSteps/StepFour.tsx
  quolance-ui/src/components/postProjectSteps/StepOne.tsx
  quolance-ui/src/components/postProjectSteps/StepThree.tsx
  quolance-ui/src/components/postProjectSteps/StepTwo.tsx
  quolance-ui/src/components/response-feedback.tsx
  quolance-ui/src/components/role-guard.tsx
  quolance-ui/src/components/ui/ServiceModal.tsx
  quolance-ui/src/components/ui/client/BusinessCategoryDropDown.tsx
  quolance-ui/src/components/ui/client/ClientBudgetRadioGroup.tsx
  quolance-ui/src/components/ui/client/DesiredExperienceLevelRadioGroup.tsx
  quolance-ui/src/components/ui/client/ExpectedDeliveryRadioGroup.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectFilter.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/env.ts
  quolance-ui/src/constants/models/http/HttpErrorResponse.ts
  quolance-ui/src/constants/models/http/PagedResponse.ts
  quolance-ui/src/constants/models/user/UserResponse.ts
  quolance-ui/src/constants/types/formTypes.ts
  quolance-ui/src/constants/types/projectTypes.ts
  quolance-ui/src/constants/types/userTypes.ts
  quolance-ui/src/lib/auth/use-auth.ts
  quolance-ui/src/lib/logger.ts
  quolance-ui/src/util/context/ReactQueryProvider.tsx
  quolance-ui/src/util/context/StepsContext.tsx
  quolance-ui/src/util/hooks/useClickOutside.tsx
  quolance-ui/src/util/hooks/useScroll.tsx
  quolance-ui/src/util/hooks/useToggle.tsx
  quolance-ui/src/util/hooks/userHooks.tsx
Labels: proposal submission, frontend

#88 Added UI and connected to backend for admin approval of project
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/AdminContext/ProjectContext.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminApproveProject/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminApproveProject/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminToastPage/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ConfirmationModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/Pagination.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectAdminCard.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
Labels: frontend

#90 [Frontend] #66: Connect UI to backend client sees project submissions
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/api/projects-api.ts
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/models/applications/ApplicationResponse.ts
Labels: proposal submission, frontend

#93 56 fe make UI for admin creates admin
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminCreateAdmin/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/CreateAdminForm.tsx
Labels: frontend

#92 #8 Improvement on UI upon password/name change #58:
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-basic-details-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/components/update-password-form.tsx
Labels: frontend

#94 A user (Freelancer/Client) can browse the current posted contracts
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/PublicController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ExpectedDeliveryTime.java
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/auth-api.ts
  quolance-ui/src/api/projects-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/my-projects/ClientProjectsView.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/freelancers/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectApplication.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
  quolance-ui/src/app/_app.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/global/BreadCrumb.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/components/home/HeroSection.tsx
  quolance-ui/src/components/postProjectSteps/StepFour.tsx
  quolance-ui/src/components/postProjectSteps/StepOne.tsx
  quolance-ui/src/components/postProjectSteps/StepThree.tsx
  quolance-ui/src/components/postProjectSteps/StepTwo.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectFilter.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/types/formTypes.ts
  quolance-ui/src/constants/types/projectTypes.ts
  quolance-ui/src/util/context/StepsContext.tsx
  quolance-ui/src/util/context/ToastProvider.tsx
Labels: frontend

#99 Added more details to frontend setup in README
  README.md
Labels: documentation

#143 added important tests, files and release demo link to readme
  README.md
Labels: documentation, README

#144 Account Verification and Related Enhancements (#138)
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserResponseDto.java
  quolance-api/src/main/resources/application.yml
  quolance-ui/next.config.js
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/components/verify-account.tsx
  quolance-ui/src/constants/models/user/UserResponse.ts
  quolance-ui/src/public/images/email_icon.svg
  quolance-ui/src/public/images/email_illustration.svg
Labels: frontend, backend, email

#146 feat: (BE-136) Freelancer can cancel (remove) his application
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ApplicationProcessWorkflow.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java
Labels: Task, backend

#148 [#139] Comprehensive OAuth2 User Registration Flow Implementation
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/PendingController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UpdatePendingUserRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/Role.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/SendTempPasswordEmailJob.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendTempPasswordEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/PendingWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/OAuth2LoginSuccessHandlerImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/PendingWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/validators/PasswordMatchValidator.java
  quolance-api/src/main/resources/mail-templates/generated-password-email.html
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/pending-user-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/page.tsx
  quolance-ui/src/constants/models/user/UserResponse.ts
Labels: user creation, user authentication, frontend, backend

#155 feat: (BE-154) Created endpoints to fetch quolance enums
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/EnumController.java
Labels: Task, backend

#152 Implemented endpoint to edit a project #118
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectUpdateDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
Labels: backend

#142 109 fe UI unauthenticated pages
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-a-freelancer/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-clients/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/contact-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/faqs/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/about-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/reviews/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/success-stories/page.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/components/ui/CollapsibleList.tsx
  quolance-ui/src/components/ui/CommentCard.tsx
  quolance-ui/src/components/ui/faqAccordion.tsx
  quolance-ui/src/components/ui/freelancers/BasicFreelancerCard.tsx
  quolance-ui/src/constants/data.ts
Labels: frontend, dashboard

#159 [Frontend] #126: make UI for updating a project
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectUpdateDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/projects-api.ts
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-clients/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/components/postProjectSteps/StepOne.tsx
  quolance-ui/src/components/postProjectSteps/StepTwo.tsx
  quolance-ui/src/components/ui/RichTextEditor.tsx
  quolance-ui/src/components/ui/ViewEditField.tsx
  quolance-ui/src/components/ui/button.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsContent.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsView.tsx
  quolance-ui/src/constants/types/form-types.ts
  quolance-ui/src/constants/types/project-types.ts
  quolance-ui/src/util/objectUtils.ts
  quolance-ui/src/util/stringUtils.ts
Labels: frontend

#165 hotfix: Added is verified true for admin in local
  quolance-api/src/main/java/com/quolance/quolance_api/configs/AdminInitializer.java
Labels: bug, backend
