Repository abdelh17/Quolance, pull requests merged in 2024-10, with the labels that each got.

#14 resolve #12 Chore : setting up frontend project with the correct framework, routing, and linting
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .huskyrc
  README.md
  commitlint.config.js
  package-lock.json
  package.json
  quolance-ui/.env.example
  quolance-ui/.eslintrc.js
  quolance-ui/.gitignore
  quolance-ui/.npmrc
  quolance-ui/.prettierignore
  quolance-ui/.prettierrc.js
  quolance-ui/README.md
  quolance-ui/jest.config.js
  quolance-ui/jest.setup.js
  quolance-ui/next-sitemap.config.js
  quolance-ui/next.config.js
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/postcss.config.mjs
  quolance-ui/public/images/404-img.png
  quolance-ui/src/__tests__/pages/404.test.tsx
  quolance-ui/src/app/(with-main-layout)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/not-found/page.tsx
  quolance-ui/src/app/_app.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/app/not-found.tsx
  quolance-ui/src/app/page.tsx
  quolance-ui/src/components/ui/LinkButton.tsx
  quolance-ui/src/constant/env.ts
  quolance-ui/src/lib/__tests__/helper.test.ts
  quolance-ui/src/lib/helper.ts
  quolance-ui/src/lib/logger.ts
  quolance-ui/src/lib/utils.ts
  quolance-ui/tailwind.config.ts
  quolance-ui/tsconfig.json
  quolance-ui/vercel.json
Labels: project creation, frontend

#16 2-3 user registration and authentication backend
  quolance-api/.gitignore
  quolance-api/.mvn/wrapper/maven-wrapper.properties
  quolance-api/mvnw
  quolance-api/mvnw.cmd
  quolance-api/pom.xml
  quolance-api/src/main/java/com/quolance/quolance_api/QuolanceApiApplication.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/JwtAuthenticationFilter.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SwaggerConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthenticationController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/LoginResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserLoginDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserRegistrationDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/AbstractEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/Role.java
  quolance-api/src/main/java/com/quolance/quolance_api/exceptions/GlobalExceptionHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/AuthenticationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/AuthenticationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/JwtService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java
  quolance-api/src/main/resources/application.properties
  quolance-api/src/test/java/com/quolance/quolance_api/QuolanceApiApplicationTests.java
Labels: user creation, user authentication, backend

#34 Update README.md
  README.md
Labels: documentation

#36 Add backend run step
  README.md
Labels: documentation

#37 BE client can post a project
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/ProjectDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/UserDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/AbstractEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ClientService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ClientServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/UserServiceImpl.java
Labels: project creation, backend

#42 Freelancer can submit a proposal for a project #5 Parent: #24
  quolance-ui/src/app/(with-main-layout)/freelancer-apply/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/page.tsx
  quolance-ui/src/components/ui/ProjectCard.tsx
  quolance-ui/src/data/data.ts
Labels: frontend

#44 #3 added bearer option on swagger
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SwaggerConfig.java
Labels: Task, backend

#47 28-BE: Client can browse project submissions
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ApplicationRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ApplicationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ClientService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ApplicationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ClientServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/FreelancerServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/impl/ProjectServiceImpl.java
Labels: Task, backend

#54 [FE #20] - Login and Sign-In Pages
  quolance-ui/src/app/(without-main-layout)/sign-in/page.tsx
  quolance-ui/src/app/(without-main-layout)/sign-up/page.tsx
  quolance-ui/src/public/images/facebook_icon.png
  quolance-ui/src/public/images/google_icon.png
Labels: frontend

#52 [BE #21] - Allow user to verify his account using a mailing service
  .gitignore
  infrastructure/docker-compose.yaml
  quolance-api/pom.xml
  quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationProperties.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/EmailConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthenticationController.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/VerificationCode.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/SendWelcomeEmailJob.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/VerificationCodeRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/EmailService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/VerificationCodeService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/AuthenticationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/EmailServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/VerificationCodeServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/ApplicationContextProvider.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/ExceptionHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/HttpErrorResponse.java
  quolance-api/src/main/resources/application.properties
  quolance-api/src/main/resources/mail-templates/welcome-email.html
Labels: user authentication, backend, technology

#53 [Frontend #23] Make UI for freelancer to see projects
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/freelancer-apply/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/freelancers/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ClientProjectsView.tsx
  quolance-ui/src/app/(with-main-layout)/projects/FreelancerProjectsView.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectApplication.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/page.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/ui/ProjectCard.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/FreelancersFilterModal.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectFilter.tsx
  quolance-ui/src/data/data.ts
  quolance-ui/src/hooks/userHooks.tsx
  quolance-ui/src/types/projectTypes.ts
  quolance-ui/src/types/userTypes.ts
  quolance-ui/src/util/Providers.tsx
Labels: frontend
