Repository abdelh17/Quolance, pull requests merged in 2025-02, with the labels that each got.

#330 bugfix: #328 Blog posts not displayed upon creation
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
Labels: bug, frontend, blog

#349 feat: #346 Enhanced Notification System & WebSocket Cleanup
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/NotificationRestController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/WebSocketController.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/MessageEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/MessageRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/NotificationRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/NotificationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/WebSocketService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/AbstractWebSocketService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/ChatMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/GreetingMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketServiceLocator.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketUtils.java
  quolance-ui/src/api/notifications-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/websockettest/page.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/ui/notifications/NotificationPanel.tsx
  quolance-ui/src/util/context/ToastProvider.tsx
  quolance-ui/src/util/context/webSocketContext.tsx
Labels: frontend, backend, Notifications

#345 bugfix: #288 Fixed backend bug where users could update or delete comments that are not theirs
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogCommentController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/BlogCommentService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogCommentServiceImpl.java
Labels: bug, backend

#342 feat: #322, #323, #324 User can post images in his blog post
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/FileEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/blog/BlogImage.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/blog/BlogPost.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/EntityCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogPostControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/BlogPostServiceUnitTest.java
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/CreatePostForm.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
Labels: frontend, backend, blog

#344 feat: #334 Add BE for Profile Completion Progress Bar
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/ProfileCompletionCalculator.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProfileField.java
Labels: backend

#348 test: #347 BE Test Suite Quality Assessment and Improvement Initiative
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/ReactionService.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/EnumControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/NotificationRestControllerUnitTest.java
Labels: backend, testing

#351 feat: #350 Add more pages and content to the website
  .gitignore
  quolance-api/logs/quolance.log.2025-02-08.0.gz
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-a-freelancer/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-clients/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/contact-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/faqs/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/about-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/reviews/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/success-stories/page.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/constants/data.ts
Labels: frontend

#343 feat: #321 Made UI for deleting a comment post reaction
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
Labels: frontend, blog

#340 feat: #326 added pagination for blog post and comments
  QuolanceAPI.postman_collection.json
  quolance-api/logs/quolance.log.2025-02-07.0.gz
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogCommentController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogCommentDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/blog/BlogCommentRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/blog/BlogPostRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/BlogCommentService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/BlogPostService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogCommentServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogCommentControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogPostControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogControllerUnitTest.java
Labels: backend, blog

#354 feat: #335 Implement UI for profile completion progress bar
  .github/workflows/main.yml
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/ProfileCompletionCalculator.java
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/EditButton.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileImageModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileProgressBar.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SaveButton.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/constants/models/user/UserResponse.ts
Labels: profile improvement, frontend

#355 feat: #325 Link user profile when viewing a blog post comment
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/UserSummary.tsx
Labels: frontend, blog

#357 feat: #338 Fix minor defects in the UI
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/api/projects-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileImageModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/FreelancerDashboardTable.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/components/ui/Pagination.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/candidates/FreelancerCatalogCard.tsx
  quolance-ui/src/components/ui/freelancers/candidates/candidateFilter/FreelancerCatalogFilter.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/constants/models/applications/ApplicationResponse.ts
  quolance-ui/src/constants/types/form-types.ts
  quolance-ui/src/util/context/ReactQueryProvider.tsx
Labels: frontend, improvement

#364 bugfix: #361 Frontend fails to build due to ESLint error
  .github/workflows/main.yml
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
Labels: bug, frontend

#366 bugfix: #365 Fixed email not sending on registration on deployed backend
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/EmailServiceImpl.java
Labels: bug, backend

#377 deploy: #367 Configured HTTPS
  .env.gpg
  quolance-api/src/main/resources/application.yml
Labels: deployment

#378 deploy: #62 Added quolance.com to allowedOrigins for CORS configs
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/resources/mail-templates/generated-password-email.html
  quolance-api/src/main/resources/mail-templates/welcome-email.html
Labels: deployment

#381 bugfix: #380 disabled ssl for local development
  quolance-api/src/main/resources/application-local.yml
Labels: bug, backend

#387 bug: #386 Updated properties configuration files
  .env.gpg
  .github/workflows/main.yml
  README.md
  quolance-api/src/main/resources/application-local.yml
  quolance-api/src/test/resources/application-test.yml
Labels: bug, backend

#388 bugfix: #379 Added temporary fix for users cant verify account in production
  infrastructure/docker-compose.yaml
  quolance-api/src/main/java/com/quolance/quolance_api/configs/AdminInitializer.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/test/resources/application-test.yml
Labels: bug, backend

#391 feat: #327 fe handle paging for comments and posts
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/constants/models/http/PagedResponse.ts
Labels: Task, frontend, blog

#396 feat: #395 Added toggle for project evaluation by AI model
  quolance-api/src/main/java/com/quolance/quolance_api/configs/FeatureToggleConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectEvaluationResult.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/FeatureToggle.java
  quolance-api/src/main/resources/toggles.properties
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
Labels: backend, logging, AI

#404 feat: #401 User can verify email by entering a code received by email
  quolance-api/src/main/java/com/quolance/quolance_api/configs/ApplicationProperties.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/VerifyEmailDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/VerificationCodeRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/VerificationCodeService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/VerificationCodeServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/main/resources/application-local.yml
  quolance-api/src/main/resources/application.yml
  quolance-api/src/main/resources/mail-templates/welcome-email.html
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/UsersControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/jobs/SendWelcomeEmailUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/page.tsx
Labels: Story, user creation, frontend, backend

#400 feat: #358 Fix/Add Filtering, Fields in Project and Application in BE
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/application/ApplicationCreateDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/application/ApplicationDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectFilterDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Application.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
Labels: backend

#397 feat: #393 Implement Notification Subscription System with UI Enhancements & Backend Fixes**
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/NotificationSubscriptionResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
  quolance-ui/src/api/notifications-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/notifications/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/NotificationSubscription.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/page.tsx
  quolance-ui/src/components/ui/notifications/NotificationPanel.tsx
  quolance-ui/src/util/context/webSocketContext.tsx
Labels: frontend, backend, Notifications

#392 feat: #363 Added logging statements in blog post related classes in BE.
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogCommentController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/ReactionController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogCommentServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/ReactionServiceImpl.java
Labels: backend

#406 test: #405 adding more cypress tests
  .github/workflows/main.yml
  quolance-ui/cypress/e2e/admin.cy.ts
  quolance-ui/cypress/e2e/client.cy.ts
  quolance-ui/cypress/e2e/login.cy.ts
  quolance-ui/cypress/e2e/registration.cy.ts
  quolance-ui/cypress/e2e/setting.cy.ts
  quolance-ui/package.json
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ConfirmationModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardActionButtons.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardTable.tsx
  quolance-ui/src/components/postProjectSteps/StepOne.tsx
  quolance-ui/src/components/ui/freelancers/ApprovalConfirmationModal.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
Labels: frontend, testing

#385 feat: #375 #383 Integrate Gemini API for Project Moderation & Project Rejection Handling
  quolance-api/logs/quolance.log.2025-02-07.0.gz
  quolance-api/src/main/java/com/quolance/quolance_api/configs/FeatureToggleConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/GeminiConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectEvaluationResult.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectRejectionDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/AiService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/GeminiService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/AdminWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectModerationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectModerationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/FeatureToggle.java
  quolance-api/src/main/resources/application.yml
  quolance-api/src/main/resources/toggles.properties
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ClientControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
Labels: project creation, backend, project approval, AI

#411 feat: #371 Improve profile page, and adjust UI pages bugs
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SaveButton.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/reviews/page.tsx
  quolance-ui/src/app/globals.css
Labels: frontend

#412 feat: #356 Improve project catalog browsing and fixed UI defects
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectPublicDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/ProjectDetails.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/candidates/CandidatesContainer.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientDashboardTable.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/ui/RichTextDisplay.tsx
  quolance-ui/src/components/ui/RichTextEditor.tsx
  quolance-ui/src/components/ui/freelancers/candidates/candidateFilter/FreelancerCatalogListType.tsx
  quolance-ui/src/components/ui/freelancers/candidates/candidateFilter/FreelancerCatalogSubListSelect.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectListLayout.tsx
  quolance-ui/src/components/ui/projects/projectFIlter/ProjectListType.tsx
  quolance-ui/src/components/ui/projects/projectFIlter/ProjectSubListSelect.tsx
  quolance-ui/src/constants/models/applications/ApplicationResponse.ts
  quolance-ui/src/constants/types/project-types.ts
Labels: frontend

#398 bug: #321 delete button not appearing for comments
  quolance-ui/src/components/ui/blog/CommentCard.tsx
Labels: frontend, blog

#413 feat: #409 Deletion of Uploaded Photos and Documents
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FileController.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/FileRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/FileService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FileControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/FileServiceUnitTest.java
Labels: backend
