Repository abdelh17/Quolance, pull requests merged in 2025-03, with the labels that each got.

#419 bugfix: #418 changed rejection after AI evaluation only if manual approval is not needed
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
Labels: bug, backend

#421 bugfix: #420 Fixed bug where bios could not be longer than 255 chars and added character counter on bio field in UI
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Profile.java
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
Labels: bug, frontend, backend

#428 test: #427 adding even more e2e cypress tests
  quolance-ui/cypress/e2e/client.cy.ts
  quolance-ui/cypress/e2e/freelancer.cy.ts
  quolance-ui/cypress/e2e/setting.cy.ts
  quolance-ui/cypress/e2e/unauthenticated.cy.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/FreelancerDashboardTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/NotificationSubscription.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-a-freelancer/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/how-it-works/find-clients/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/contact-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/faqs/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/about-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/why-quolance/reviews/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/components/global/Footer.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/home/HeroSection.tsx
  quolance-ui/src/components/ui/Modal.tsx
  quolance-ui/src/components/ui/Pagination.tsx
  quolance-ui/src/components/ui/RichTextDisplay.tsx
  quolance-ui/src/components/ui/applications/ApplicationStatusBadge.tsx
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/RefuseSubmissionsModal.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsContent.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/components/ui/projects/ProjectListLayout.tsx
  quolance-ui/src/components/ui/projects/projectFIlter/ProjectFilter.tsx
  quolance-ui/src/components/ui/projects/projectFIlter/ProjectSubListSelect.tsx
Labels: Task, frontend, testing

#426 feat: #422 Added basic implementation for chat system
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/chat/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/MessageDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/SendMessageDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/chat/Message.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/chat/MessageRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
  quolance-api/src/main/resources/toggles.properties
Labels: backend, chat system

#431 feat: #430 Clients see the status of their project on creation
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectEvaluationResult.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx
  quolance-ui/src/components/ProjectStatusNotification.tsx
Labels: project creation, frontend, backend, project approval

#425 bugfix: #424 Fixed OAuth2 SSO broken due to recent changes
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/OAuth2LoginSuccessHandlerImpl.java
  quolance-api/src/main/resources/application-local.yml
  quolance-api/src/main/resources/application.yml
Labels: bug, user authentication

#423 feat: #369 Add more fields to Freelancer Profile
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/UpdateFreelancerProfileDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Profile.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/profile/ProjectExperience.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/profile/WorkExperience.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
Labels: Task, profile improvement, backend

#432 feat: #370 Add new public profile for freelancer, and improve existing edit profile page
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/candidates/CandidatesContainer.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/freelancers/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileProgressBar.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProjectExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProjectField.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/public-profile/[username]/page.tsx
  quolance-ui/src/components/ui/StarRating.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/UserSummary.tsx
  quolance-ui/src/constants/models/candidates/CandidateResponse.ts
  quolance-ui/src/constants/models/user/UserResponse.ts
  quolance-ui/src/util/stringUtils.ts
Labels: frontend

#433 test: #429 Added Unit Tests for the Reaction and Comment controllers as well as the service layers in BE
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogCommentControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogReactionControllerUnitTests.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/BlogCommentServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectModerationServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ReactionServiceUnitTests.java
Labels: backend, testing

#442 chore: #441 update github and google secrets
  .env.gpg
Labels: deployment

#443 bugfix: #440 Clients see in their dashboards other client projects
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
Labels: bug, backend

#446 bugfix: #444 Username null in Client getAllFreelancers
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
Labels: bug, backend

#466 feat: #422 Added polling to chat system
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Message.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/MessageEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/MessageRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/chat/MessageRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
  quolance-ui/src/api/chat-api.ts
  quolance-ui/src/constants/types/chat-types.ts
Labels: frontend, backend, chat system

#468 feat: #445 Add Notification Integration Across Workflow Service Implementations
  quolance-api/pom.xml
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/NoOpNotificationConfig.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/UsersControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ApplicationProcessWorkflowUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
Labels: Task, backend

#467 bugfix: #460 Github OAuth2 Fix
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/shared/auth-components.tsx
Labels: bug, user authentication

#473 feat: #422 added get contacts endpoint
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/ContactDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/MessageRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
Labels: backend, chat system

#472 feat: #457 added profile completion status banner to freelancer dashboard
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/ProfileCompletionCalculator.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProfileField.java
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileImageModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/UpdateProfileModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
Labels: Task, profile improvement, frontend

#478 bugfix: #477 fixed profile pictures' shape for both blog posts and comments
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/UserSummary.tsx
Labels: bug, frontend, blog

#475 feat: #439 Made UI for editing a comment post
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/CreatePostForm.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
Labels: frontend, blog

#480 feat: #373 Implement BE for User Account Deletion
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/UserDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ApplicationStatus.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/ProjectStatus.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ApplicationRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
Labels: backend, user deletion

#476 bugfix: #362 Fix Log Errors in Exception Tests for Services
  quolance-api/src/test/resources/logback-test.xml
Labels: bug, backend, testing

#481 feat: #408 Added a chatbot to reply to user questions
  quolance-api/pom.xml
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatbotController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ChatRequest.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/AiService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/GeminiService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/ChatbotService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatbotServiceImpl.java
  quolance-api/src/main/resources/faq.txt
  quolance-api/src/main/resources/toggles.properties
  quolance-ui/src/api/chatbot-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/Chatbot.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
Labels: frontend, backend, AI, chatbot

#479 feat: #434 Create UI for chat system
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/ContactDto.java
  quolance-api/src/main/resources/toggles.properties
  quolance-ui/src/api/chat-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/ui/chat/Avatar.tsx
  quolance-ui/src/components/ui/chat/ChatContact.tsx
  quolance-ui/src/components/ui/chat/ChatContainer.tsx
  quolance-ui/src/components/ui/chat/ChatHeader.tsx
  quolance-ui/src/components/ui/chat/ChatInput.tsx
  quolance-ui/src/components/ui/chat/ChatProvider.tsx
  quolance-ui/src/components/ui/chat/ChatUserCard.tsx
  quolance-ui/src/components/ui/chat/ContactsContainer.tsx
  quolance-ui/src/components/ui/chat/ContactsHeader.tsx
  quolance-ui/src/components/ui/chat/GenericChatContainer.tsx
  quolance-ui/src/components/ui/chat/GenericChatHeader.tsx
  quolance-ui/src/components/ui/chat/Message.tsx
  quolance-ui/src/components/ui/chat/MessageGroup.tsx
  quolance-ui/src/components/ui/chat/MessageList.tsx
  quolance-ui/src/components/ui/chat/MessageTimestampSeperator.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/candidates/FreelancerListLayout.tsx
  quolance-ui/src/constants/types/chat-types.ts
  quolance-ui/src/public/images/chatbot_icon.png
  quolance-ui/src/public/images/conversation_illustration.png
  quolance-ui/src/util/chatUtils.ts
  quolance-ui/src/util/stringUtils.ts
Labels: frontend, chat system

#483 feat: #456 A Client can review a Freelancer
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/profile/FreelancerProfileDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/review/ReviewCreateDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/review/ReviewDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Review.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ReviewRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/ClientWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ReviewService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ReviewServiceImpl.java
Labels: backend

#471 feat : #469 #470 Fix UI bugs, Improve dashboard tables
  quolance-ui/cypress/e2e/freelancer.cy.ts
  quolance-ui/cypress/e2e/unauthenticated.cy.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientCandidatesListTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/ClientProjectsListTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/FreelancerDashboardTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectListLayout.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/types/project-types.ts
Labels: frontend, dashboard, improvement

#474 feat: #448 #451 User can report a Blog post and admin can evaluate it
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/blog/BlogPost.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/blog/BlogPostRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/AdminWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/blog/BlogPostService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/AdminContext/ReportedBlogContext.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/AdminContext/ResolvedBlogContext.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminReportedBlogPosts/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminReportedBlogPosts/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminResolvedBlogPosts/[id]/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/adminResolvedBlogPosts/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/adminDashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/AdminReportedPostDetail.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/PostReaction.tsx
Labels: frontend, backend, blog

#484 feat: #482 Combined chatbot with chat system
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatbotServiceImpl.java
  quolance-api/src/main/resources/toggles.properties
  quolance-ui/src/api/chat-api.ts
  quolance-ui/src/api/chatbot-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/Chatbot.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
  quolance-ui/src/components/ui/chat/ChatContainer.tsx
  quolance-ui/src/components/ui/chat/ChatProvider.tsx
  quolance-ui/src/components/ui/chat/ChatUserCard.tsx
  quolance-ui/src/util/chatUtils.ts
Labels: AI, chatbot, chat system

#490 feat: #455 make UI for client rating on a freelancer profile
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/review/ReviewDto.java
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ReviewCard.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/public-profile/[username]/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/components/ui/freelancers/AddReviewModal.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/constants/models/candidates/CandidateResponse.ts
  quolance-ui/src/constants/models/user/UserResponse.ts
Labels: Task, frontend, ratings

#494 bugfix: Removed logging from chat system
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ChatController.java
Labels: bug

#497 bugfix: #485 fixed Trying to get a profile of a client throw error
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/FileServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectModerationServiceUnitTest.java
  quolance-api/src/test/resources/logback-test.xml
Labels: bug, backend

#493 feat: #491 - Comprehensive AI-Driven Text Generation & Prompt Strategy Enhancements
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/TextGenerationController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/text/GenerateApplicationLetterDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/text/GenerateTextDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/PromptType.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/TextGenerationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/impl/TextGenerationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/prompts/AboutPromptStrategy.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/prompts/ApplicationPromptStrategy.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/prompts/ProjectPromptStrategy.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/prompts/PromptStrategy.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/text/prompts/PromptStrategyRegistry.java
  quolance-api/src/main/resources/application.yml
  quolance-ui/.eslintrc.js
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/textGeneration-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/ui/AiPromptModal.tsx
  quolance-ui/src/components/ui/LargeModal.tsx
Labels: project creation, proposal submission, profile improvement, frontend, backend, AI
