Repository abdelh17/Quolance, pull requests merged in 2025-04, with the labels that each got.

#498 refactor #492: Moved all model files to /src
  quolance-ui/src/api/auth-api.ts
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/api/chat-api.ts
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/api/textGeneration-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/componentsAdmin/CreateAdminForm.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/LanguageSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileStatus.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProjectExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/WorkExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/pending-user-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/ChangePassword.tsx
  quolance-ui/src/app/(with-main-layout)/projects/ProjectsContainer.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(admin-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/layout.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/components/user-auth-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/AuthHeader.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx
  quolance-ui/src/components/error-feedback.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/components/permission-guard.tsx
  quolance-ui/src/components/response-feedback.tsx
  quolance-ui/src/components/role-guard.tsx
  quolance-ui/src/components/ui/blog/UserSummary.tsx
  quolance-ui/src/components/ui/chat/ContactsContainer.tsx
  quolance-ui/src/components/ui/freelancers/AddReviewModal.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/candidates/FreelancerCatalogCard.tsx
  quolance-ui/src/components/ui/freelancers/candidates/FreelancerListLayout.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/components/ui/projects/projectFIlter/ProjectSubListSelect.tsx
  quolance-ui/src/models/applications/ApplicationResponse.ts
  quolance-ui/src/models/candidates/CandidateResponse.ts
  quolance-ui/src/models/http/HttpErrorResponse.ts
  quolance-ui/src/models/http/PagedResponse.ts
  quolance-ui/src/models/user/UserResponse.ts
  quolance-ui/src/util/CandidateSelectionUtils.tsx
  quolance-ui/src/util/utils.ts
Labels: frontend

#500 bugfix: #499 Freelancer created with OAuth2 does not have an associated profile
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/PendingWorkflowServiceImpl.java
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
Labels: bug

#502 feat: #501 AI-Powered Freelancer Recommendation Engine and Enhanced UI
  quolance-api/src/main/java/com/quolance/quolance_api/configs/GeminiConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/RecommendationController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/recommendation/FreelancerRecommendationDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Profile.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/GeminiEmbeddingService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/recommendation/ProfileEmbeddingService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/ai_models/recommendation/RecommendationService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ApplicationProcessWorkflowImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/ClientWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/SimilarityUtils.java
  quolance-api/src/main/resources/application.yml
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/client-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/TopTalent.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/components/postProjectSteps/StepOne.tsx
  quolance-ui/src/components/ui/AiPromptModal.tsx
  quolance-ui/src/components/ui/LargeModal.tsx
  quolance-ui/src/components/ui/freelancers/TopTalentFreelancerCard.tsx
  quolance-ui/src/models/user/UserResponse.ts
Labels: frontend, backend, AI

#507 feat: #505 Added Password Requirements on Registration
  quolance-ui/cypress/e2e/registration.cy.ts
  quolance-ui/src/app/(without-main-layout)/auth/register/components/PasswordRequirement.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
Labels: user creation, frontend

#517 feat: #516 Added questions to FAQ and made it more interactive
  quolance-api/src/main/resources/application.yml
  quolance-api/src/main/resources/mail-templates/welcome-email.html
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/faqs/page.tsx
  quolance-ui/src/components/home/HeroSection.tsx
Labels: frontend, improvement

#515 feat: #514 Updated terms of service and privacy policy
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/privacy-policy/page.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/terms-of-service/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/login/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/components/global/MobileMenu.tsx
  quolance-ui/src/constants/data.ts
  quolance-ui/src/constants/header-data.ts
Labels: frontend

#513 feat: #510 Users can request a new verification code
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/VerificationCodeService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/VerificationCodeServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/page.tsx
Labels: user authentication, frontend, backend

#519 bugfix: #516 fix cypress tests
  quolance-ui/cypress/e2e/unauthenticated.cy.ts
Labels: bug, frontend, testing

#523 feat: #522 Made Password Validation Consistent Across All User Flows
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/components/update-password-and-role-form.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/setting/components/ChangePassword.tsx
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
Labels: frontend

#520 feat: #518 moved Blog page from unauthenticated pages to authenticated pages
  quolance-ui/cypress/e2e/unauthenticated.cy.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/blog/page.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/constants/header-data.ts
Labels: frontend

#530 feat: #503 Fix UI defects v3
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/chat/ContactDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/chat/impl/ChatServiceImpl.java
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/WorkExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/FreelancerApplicationsListTable.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/dashboard/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/public-profile/[username]/page.tsx
  quolance-ui/src/app/(with-main-layout)/layout.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/globals.css
  quolance-ui/src/app/layout.tsx
  quolance-ui/src/components/ui/ComboListBox.tsx
  quolance-ui/src/components/ui/LargeModal.tsx
  quolance-ui/src/components/ui/Tooltip.tsx
  quolance-ui/src/components/ui/chat/ChatContact.tsx
  quolance-ui/src/components/ui/chat/ChatProvider.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/freelancers/FreelancersFilterModal.tsx
  quolance-ui/src/components/ui/freelancers/candidates/FreelancerCatalogCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/components/ui/projects/ProjectListLayout.tsx
  quolance-ui/src/constants/types/chat-types.ts
  quolance-ui/src/lib/validation/projectSchema.ts
  quolance-ui/src/util/CandidateSelectionUtils.tsx
  quolance-ui/src/util/hooks/useWindowDimensions.tsx
Labels: frontend

#528 feat: #527 Updated post ordering
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/blog/BlogPostRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/EntityCreationHelper.java
Labels: backend, blog, improvement

#533 feat: #532 Improved the email verification process
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/users/VerifyEmailDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/UserService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/main/resources/mail-templates/welcome-email.html
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/[email]/page.tsx
  quolance-ui/src/app/(without-main-layout)/auth/verify-email/components/verification-code.tsx
  quolance-ui/src/components/verify-account.tsx
Labels: user creation, user authentication, frontend, backend, improvement

#535 feat: #463 Added checkbox to make client remove liability from us when creating a project
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/components/postProjectSteps/StepFour.tsx
Labels: frontend, improvement

#536 bugfix: #463 Removed double account sign in redirect
  quolance-ui/src/app/(without-main-layout)/auth/register/page.tsx
Labels: bug, frontend

#541 bugfix: Added back auto recommendation that was removed
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
Labels: bug, frontend

#554 bug: #553 Fixed bug where email variable in URL for email verification is undefined
  quolance-ui/src/app/(without-main-layout)/auth/register/components/register-form.tsx
Labels: bug, frontend

#550 bugfix: #549 read more button doesn't appear on blogposts in production
  quolance-ui/src/components/ui/blog/PostCard.tsx
Labels: bug, frontend, blog

#552 bugfix: #551 Fixed Blog posts text appears compressed on mobile devices
  quolance-ui/src/components/ui/blog/PostCard.tsx
Labels: bug, frontend, blog

#563 bugfix: #562 minor UI defects and missing elements
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/UserSummary.tsx
Labels: bug, frontend, blog

#561 feat: #560 added support for tags editing in blog posts
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostUpdateDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/blog/BlogPostServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/BlogControllerUnitTest.java
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/CreatePostForm.tsx
Labels: frontend, backend, blog

#567 refactor: #566 Refactored blog
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/CreatePostModal.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/constants/types/blog-types.ts
Labels: frontend, blog

#571 test:#570 fixing and adding cypress frontend tests
  quolance-ui/cypress/e2e/client.cy.ts
  quolance-ui/cypress/e2e/freelancer.cy.ts
  quolance-ui/cypress/e2e/registration.cy.ts
  quolance-ui/cypress/e2e/unauthenticated.cy.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/EditButton.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/LanguageSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProjectExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SaveButton.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/WorkExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/support/contact-us/page.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
Labels: Task, frontend, testing

#572 documentation: Updated readme for final release
  README.md
Labels: documentation, README

#573 test: #548 Add new tests and test classes
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/EntityCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AuthControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ChatControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/PublicControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/UsersControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/ChatControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/auth/VerificationCodeServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ReviewServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
Labels: backend, testing, improvement
