Repository abdelh17/Quolance, pull requests merged in 2025-01, with the labels that each got.

#236 bugfix: Ensure Welcome Email Job Waits for User Transaction Completion for #200
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendTempPasswordEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/EmailServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
Labels: backend, blog

#241 bugfix: Refined welcome email thrown exception fix
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
Labels: backend, blog

#255 Implement project filtering with pagination support
  QuolanceAPI.postman_collection.json
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/PublicController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/project/ProjectFilterDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/ProjectRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/AdminWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/AdminWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/ProjectService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java
Labels: Task, backend, filtering

#254 fix: Fixed UI defects in the app for #226
  quolance-ui/src/app/(with-main-layout)/projects/[id]/FreelancerApplicationForm.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/ProjectSubmissions.tsx
  quolance-ui/src/app/(with-main-layout)/projects/[id]/page.tsx
  quolance-ui/src/app/(without-main-layout)/(authenticated-pages)/(client-protected-pages)/post-project/page.tsx
  quolance-ui/src/components/postProjectSteps/StepFour.tsx
  quolance-ui/src/components/ui/freelancers/FreelancerCard.tsx
  quolance-ui/src/components/ui/projects/ProjectCard.tsx
  quolance-ui/src/components/ui/projects/ProjectDetailsHeader.tsx
  quolance-ui/src/constants/models/applications/ApplicationResponse.ts
  quolance-ui/src/constants/models/user/UserResponse.ts
  quolance-ui/src/util/stringUtils.ts
Labels: bug, frontend

#260 feat: Notification Systems And Comprehensive Enhancements to WebSocket
  quolance-api/src/main/java/com/quolance/quolance_api/configs/WebSocketConfig.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/NotificationRestController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/WebSocketController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/NotificationResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/websocket/SendNotificationRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/MessageEntity.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Notification.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/MessageType.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/NotificationRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/WebSocketService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/AbstractWebSocketService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/ChatMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/GreetingMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/websockets/impl/NotificationMessageService.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/validators/PasswordMatch.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketServiceLocator.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/websockets/WebSocketUtils.java
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/websockettest/page.tsx
Labels: backend, improvement

#266 feat: Implement File Service with Tests and Pagination for #264, #265
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FileController.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/FileRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/FileService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ApplicationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/EnumControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FileControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/AdminWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ApplicationProcessWorkflowUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/ClientWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ApplicationServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/FileServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/UserServiceUnitTest.java
Labels: backend, testing

#281 feat: Users are able to login with both username and email for #235
  quolance-api/src/main/java/com/quolance/quolance_api/configs/CustomUserDetailsService.java
  quolance-api/src/main/java/com/quolance/quolance_api/configs/SecurityConfiguration.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/LoginRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/repositories/UserRepository.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/auth/impl/AuthServiceImpl.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogCommentControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogPostControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
Labels: backend

#273 feat: fe make UI for posting a blog post #231
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/CreatePostForm.tsx
  quolance-ui/src/components/ui/blog/CreatePostModal.tsx
  quolance-ui/src/constants/types/blog-types.ts
Labels: frontend

#279 feat: Improve freelancer profile UI page and integrate with backend for #131
  quolance-ui/src/api/freelancer-api.ts
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AboutSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/AvailabilitySection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ContactSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ExperienceSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileHeader.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/ProfileImageModal.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/components/SkillsSection.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/(freelancer-protect-pages)/profile/page.tsx
  quolance-ui/src/app/(with-main-layout)/(authenticated-pages)/profile/page.tsx
  quolance-ui/src/components/global/Header.tsx
  quolance-ui/src/constants/models/user/UserResponse.ts
Labels: frontend

#275 fix: make UI for viewing blog posts #124
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/app/(with-main-layout)/(unauthenticated-pages)/whats-new/blog/page.tsx
  quolance-ui/src/components/ui/blog/BlogContainer.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/constants/types/blog-types.ts
Labels: frontend

#298 feat: #262 Added detailed logging info
  .github/workflows/main.yml
  quolance-api/src/main/java/com/quolance/quolance_api/jobs/handlers/SendWelcomeEmailJobHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ApplicationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/main/resources/application.yml
Labels: backend

#299 docs: Update README.md to add .env data
  README.md
Labels: documentation, README

#291 feat: #249 Make UI for leaving reactions on a post
  quolance-ui/package-lock.json
  quolance-ui/package.json
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/components/ui/blog/PostReaction.tsx
Labels: Task, frontend, blog

#306 bugfix: #304 Fixed integration tests failing due to foreign key constraints on table "projects"
  quolance-api/src/main/java/com/quolance/quolance_api/entities/User.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/AuthControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogCommentControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
Labels: bug, backend, testing

#297 feat: #251 Users can set tags to their post
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/blog/BlogPostController.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostRequestDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostResponseDto.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/BlogPost.java
  quolance-api/src/main/java/com/quolance/quolance_api/entities/enums/BlogTags.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/BlogPostService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/exceptions/GlobalExceptionHandler.java
  quolance-api/src/main/java/com/quolance/quolance_api/util/exceptions/InvalidBlogTagException.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/BlogPostControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/BlogPostServiceUnitTest.java
Labels: blog

#286 feat: #246 make UI for leaving comment on post
  quolance-ui/src/api/blog-api.ts
  quolance-ui/src/components/ui/blog/CommentCard.tsx
  quolance-ui/src/components/ui/blog/PostCard.tsx
  quolance-ui/src/constants/types/blog-types.ts
Labels: Task, frontend, blog

#312 doc: Added documentation for release 2
  README.md
Labels: documentation

#315 feat: #313 Added logging statements to view requestor details
  .gitignore
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AdminController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/AuthController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/ClientController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FileController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/PendingController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/PublicController.java
  quolance-api/src/main/java/com/quolance/quolance_api/controllers/UsersController.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/FreelancerWorkflowService.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ApplicationServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/ProjectServiceImpl.java
  quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/UserServiceImpl.java
  quolance-api/src/main/resources/application.yml
  quolance-api/src/test/java/com/quolance/quolance_api/integration/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/UsersControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AdminControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/AuthControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/FreelancerControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/PublicControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/controllers/UsersControllerUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/business_workflow/FreelancerWorkflowServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ApplicationServiceUnitTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/unit/services/entity_services/ProjectServiceUnitTest.java
Labels: backend, logging

#317 refactor: #314 Extract session creation into helper class and add abstract base class for integration tests
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/EntityCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/helpers/integration/SessionCreationHelper.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/BaseIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AdminControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/AuthControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogCommentControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogPostControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/BlogReactionsControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/ClientControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/FreelancerControllerIntegrationTest.java
  quolance-api/src/test/java/com/quolance/quolance_api/integration/tests/UsersControllerIntegrationTest.java
Labels: backend, testing
